name: angular_quill
description: Angular dart component for the Quill rich text editor. Quill is a free, open source WYSIWYG editor built for the modern web.
version: 1.0.0
homepage: https://github.com/adamlofts/angular_quill

environment:
  sdk: '>=2.11.99 <3.0.0'

dependencies:
  ngdart: ^7.0.0
  ngforms: ^4.0.0
  js: ^0.6.0

